# environment.yml
name: dockerfile
channels:
  - conda-forge
  - defaults
dependencies:
    - pandas=2.2.2
    - pandera=0.20.4
    - python=3.11
    - pip ##latest version of pips
    - pip:
      - deepchecks==0.18.1